CREATE ROLE "CRM_USER" LOGIN PASSWORD 'CRM_USER' SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;
CREATE ROLE "BILLING_USER" LOGIN PASSWORD 'BILLING_USER' SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;
CREATE ROLE "TAR_CRM_USER" LOGIN PASSWORD 'TAR_CRM_USER' SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;
CREATE ROLE "TAR_BILLING_USER" LOGIN PASSWORD 'TAR_BILLING_USER' SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;