--BE
INSERT INTO ${@schema}.business_entities (be_name, be_description, be_id, be_created_by, be_creation_date, be_last_updated_date, be_last_updated_by, be_status) SELECT 'Customer', 'This is a Business Entity that manages customer data.', nextval('${@schema}.business_entities_be_id_seq'::regclass), 'admin', now(), now(), 'admin', 'Active' where not exists (select 1 from ${@schema}.business_entities where be_name='Customer');
-- Source Env
INSERT INTO ${@schema}.environment_products (environment_product_id, environment_id, product_id, product_version, created_by, creation_date, last_updated_date, last_updated_by, status, data_center_name) SELECT nextval('${@schema}.environment_product_id_seq'::regclass), 1, 1, '1', 'admin', now(), now(), 'admin', 'Active', ''  where not exists (select 1 from ${@schema}.environment_products where environment_id=1 and product_id=1);
INSERT INTO ${@schema}.environment_products (environment_product_id, environment_id, product_id, product_version, created_by, creation_date, last_updated_date, last_updated_by, status, data_center_name) SELECT nextval('${@schema}.environment_product_id_seq'::regclass), 1, 2, 'PROD', 'admin', now(), now(), 'admin', 'Active', ''  where not exists (select 1 from ${@schema}.environment_products where environment_id=1 and product_id=2);
-- Target Env
INSERT INTO ${@schema}.environment_products (environment_product_id, environment_id, product_id, product_version, created_by, creation_date, last_updated_date, last_updated_by, status, data_center_name) SELECT nextval('${@schema}.environment_product_id_seq'::regclass), 2, 1, '1', 'admin', now(), now(), 'admin', 'Active', ''  where not exists (select 1 from ${@schema}.environment_products where environment_id=2 and product_id=1);
INSERT INTO ${@schema}.environment_products (environment_product_id, environment_id, product_id, product_version, created_by, creation_date, last_updated_date, last_updated_by, status, data_center_name) SELECT nextval('${@schema}.environment_product_id_seq'::regclass), 2, 2, 'PROD', 'admin', now(), now(), 'admin', 'Active', ''  where not exists (select 1 from ${@schema}.environment_products where environment_id=2 and product_id=2);
INSERT INTO ${@schema}.environment_products (environment_product_id, environment_id, product_id, product_version, created_by, creation_date, last_updated_date, last_updated_by, status, data_center_name) SELECT nextval('${@schema}.environment_product_id_seq'::regclass), 3, 1, '1', 'admin', now(), now(), 'admin', 'Active', ''  where not exists (select 1 from ${@schema}.environment_products where environment_id=3 and product_id=1);
INSERT INTO ${@schema}.environment_products (environment_product_id, environment_id, product_id, product_version, created_by, creation_date, last_updated_date, last_updated_by, status, data_center_name) SELECT nextval('${@schema}.environment_product_id_seq'::regclass), 3, 2, 'PROD', 'admin', now(), now(), 'admin', 'Active', ''  where not exists (select 1 from ${@schema}.environment_products where environment_id=3 and product_id=2);
--Synthetic Env
INSERT INTO ${@schema}.environment_products (environment_product_id, environment_id, product_id, product_version, created_by, creation_date, last_updated_date, last_updated_by, status, data_center_name) SELECT nextval('${@schema}.environment_product_id_seq'::regclass), -1,  1, 'Synthetic', 'admin', now(), now(), 'admin', 'Active', ''  where not exists (select 1 from ${@schema}.environment_products where environment_id=-1 and product_id=1);
INSERT INTO ${@schema}.environment_products (environment_product_id, environment_id, product_id, product_version, created_by, creation_date, last_updated_date, last_updated_by, status, data_center_name) SELECT nextval('${@schema}.environment_product_id_seq'::regclass), -1, 2, 'Synthetic', 'admin', now(), now(), 'admin', 'Active', ''  where not exists (select 1 from ${@schema}.environment_products where environment_id=-1 and product_id=2);
--AI Env
INSERT INTO ${@schema}.environment_products (environment_product_id, environment_id, product_id, product_version, created_by, creation_date, last_updated_date, last_updated_by, status, data_center_name) SELECT nextval('${@schema}.environment_product_id_seq'::regclass), -2,  1, 'AI', 'admin', now(), now(), 'admin', 'Active', ''  where not exists (select 1 from ${@schema}.environment_products where environment_id=-2 and product_id=1);

-- Fix the insert to environment for  UAT - set the masking sensitive data to false
INSERT INTO ${@schema}.environments (environment_name, environment_description, environment_expiration_date, environment_point_of_contact_first_name, environment_point_of_contact_last_name, environment_point_of_contact_phone1, environment_point_of_contact_phone2, environment_point_of_contact_email, environment_id, environment_created_by, environment_creation_date, environment_last_updated_date, environment_last_updated_by, environment_status, allow_write, allow_read, sync_mode) SELECT 'Production', 'This is a Source environment.', NULL, NULL, NULL, NULL, NULL, NULL,  nextval('${@schema}.environments_environment_id_seq'::regclass), 'admin', now(),  now(), 'admin', 'Active', false, true, 'ON' where not exists (select 1 from ${@schema}.environments where environment_name='Production');
INSERT INTO ${@schema}.environments (environment_name, environment_description, environment_expiration_date, environment_point_of_contact_first_name, environment_point_of_contact_last_name, environment_point_of_contact_phone1, environment_point_of_contact_phone2, environment_point_of_contact_email, environment_id, environment_created_by, environment_creation_date, environment_last_updated_date, environment_last_updated_by, environment_status, allow_write, allow_read, sync_mode, mask_sensitive_data) SELECT 'UAT', 'This is both Source & Target environment.', NULL, NULL, NULL, NULL, NULL, NULL,  nextval('${@schema}.environments_environment_id_seq'::regclass), 'admin', now(), now(), 'admin', 'Active', true, true, 'ON', false where not exists (select 1 from ${@schema}.environments where environment_name='UAT');
INSERT INTO ${@schema}.environments (environment_name, environment_description, environment_expiration_date, environment_point_of_contact_first_name, environment_point_of_contact_last_name, environment_point_of_contact_phone1, environment_point_of_contact_phone2, environment_point_of_contact_email, environment_id, environment_created_by, environment_creation_date, environment_last_updated_date, environment_last_updated_by, environment_status, allow_write, allow_read, sync_mode, mask_sensitive_data) SELECT 'QA', 'This is a Target environment.', NULL, NULL, NULL, NULL, NULL, NULL,  nextval('${@schema}.environments_environment_id_seq'::regclass), 'admin', now(), now(), 'admin', 'Active', true, false, 'ON', false where not exists (select 1 from ${@schema}.environments where environment_name='QA');

INSERT INTO ${@schema}.product_logical_units (lu_name, lu_description, be_id, lu_parent_id, lu_id, product_name, lu_parent_name, product_id) SELECT 'Customer', 'This is the Parent LU.', 1, NULL, nextval('${@schema}.product_logical_units_lu_id_seq'::regclass), 'CRM', NULL, 1 where not exists (select 1 from ${@schema}.product_logical_units where lu_name='Customer');
INSERT INTO ${@schema}.product_logical_units (lu_name, lu_description, be_id, lu_parent_id, lu_id, product_name, lu_parent_name, product_id) SELECT 'Billing', 'This is a Child LU.', 1, 1, nextval('${@schema}.product_logical_units_lu_id_seq'::regclass), 'Billing', 'Customer', 2 where not exists (select 1 from ${@schema}.product_logical_units where lu_name='Billing');

INSERT INTO ${@schema}.products (product_name, product_description,  product_versions, product_id, product_created_by, product_creation_date, product_last_updated_date, product_last_updated_by, product_status) SELECT 'CRM', 'CRM Application', '1',  nextval('${@schema}.products_product_id_seq'::regclass), 'admin', now(), now(), 'admin', 'Active' where not exists (select 1 from ${@schema}.products where product_name='CRM');
INSERT INTO ${@schema}.products (product_name, product_description,  product_versions, product_id, product_created_by, product_creation_date, product_last_updated_date, product_last_updated_by, product_status) SELECT 'Billing', 'Billing Application', 'PROD',  nextval('${@schema}.products_product_id_seq'::regclass), 'admin', now(), now(), 'admin', 'Active' where not exists (select 1 from ${@schema}.products where product_name='Billing');

INSERT INTO ${@schema}.tdm_be_exe_process (process_id, process_name, process_description, be_id, execution_order,process_type,lu_name) SELECT nextval('${@schema}.exe_process_id_seq'::regclass), 'postTaskExePrintToLog', 'This is a Post Execution Process Flow.', 1, 1,'post','Customer' where not exists (select 1 from ${@schema}.tdm_be_exe_process where process_name='postTaskExePrintToLog');
INSERT INTO ${@schema}.tdm_be_exe_process (process_id, process_name, process_description, be_id, execution_order,process_type,lu_name) SELECT nextval('${@schema}.exe_process_id_seq'::regclass), 'preTaskExePrintToLog', 'This is a Pre Execution Process Flow.', 1, 1,'pre','Customer' where not exists (select 1 from ${@schema}.tdm_be_exe_process where process_name='preTaskExePrintToLog');

INSERT INTO ${@schema}.environment_owners (environment_id, user_type, user_name, user_id) SELECT 2, 'GROUP', 'TDM Environment Owner & Task Creator', 'TDM Environment Owner & Task Creator' WHERE NOT EXISTS (SELECT 1 FROM ${@schema}.environment_owners WHERE environment_id = 2 AND user_name = 'TDM Environment Owner & Task Creator');

INSERT INTO ${@schema}.environment_role_users(environment_id, role_id, user_type, username, user_id) VALUES (1, 1, 'ID', 'ALL', '-1') ON CONFLICT DO NOTHING;

INSERT INTO ${@schema}.environment_roles(environment_id, role_name, role_description, allowed_delete_before_load, 
	allowed_creation_of_synthetic_data,allowed_random_entity_selection,allowed_request_of_fresh_data,
	allowed_task_scheduling,allowed_number_of_entities_to_copy, role_id, role_created_by, role_creation_date, 
	role_last_updated_date,role_last_updated_by,role_status,allowed_refresh_reference_data, allowed_replace_sequences, 
	allow_read, allow_write,allowed_number_of_entities_to_read, allowed_entity_versioning, allowed_test_conn_failure, 
	allowed_number_of_reserved_entities) VALUES(1,'Production Testers','Permission set for Production environment testers',
	false,false,true,true,true,0,1,
	'admin',NOW(),NOW(),'admin','Active',true,false,true,false,-1,true,true,0) ON CONFLICT DO NOTHING;

INSERT INTO ${@schema}.environment_role_users(environment_id, role_id, user_type, username, user_id) VALUES (3, 2, 'ID', 'ALL', '-1') ON CONFLICT DO NOTHING;

INSERT INTO ${@schema}.environment_roles(environment_id, role_name, role_description, allowed_delete_before_load, 
	allowed_creation_of_synthetic_data,allowed_random_entity_selection,allowed_request_of_fresh_data,
	allowed_task_scheduling,allowed_number_of_entities_to_copy, role_id, role_created_by, role_creation_date, 
	role_last_updated_date,role_last_updated_by,role_status,allowed_refresh_reference_data, allowed_replace_sequences, 
	allow_read, allow_write,allowed_number_of_entities_to_read, allowed_entity_versioning, allowed_test_conn_failure, 
	allowed_number_of_reserved_entities) VALUES(3,'QA Testers','Permission set for QA environment testers',
	true,true,true,true,true,-1,2,
	'admin',NOW(),NOW(),'admin','Active',true,true,false,true,0,true,true,1000) ON CONFLICT DO NOTHING;

SELECT pg_catalog.setval('${@schema}.environment_roles_role_id_seq'::regclass,2);